import { Content } from "./types/milogin";

const pageContent: Content = {
  zh_CN: {
    title: "小米帐号登录",
    accountPlaceholderSMS: "手机号码",
    accountPlaceholder: "邮箱/手机号码/小米ID",
    passwordPlaceholderSMS: "短信验证码",
    passwordPlaceholder: "密码",
    codeMsg: "获取验证码",
    codeMsgRetry: "重新发送",
    loginBtnSMS: "立即登录/注册",
    loginBtn: "登录",
    toggleBtnSMS: "用户名密码登录",
    toggleBtn: "手机短信登录/注册",
    errMsgEmptyVerificationCode: "请输入短信验证码",
    errMsgInvalidVerificationCode: "短信验证码不正确",
    errMsgEmptyPhoneNumber: "请输入手机号",
    errMsgInvalidPhoneNumber: "手机号格式不正确",
    errMsgEmptyAccount: "请输入帐号",
    errMsgEmptyPassword: "请输入密码",
    registerTip: "立即注册",
    forgotPassword: "忘记密码？",
    otherLoginType: "其他方式登录",
    FAQ: "常见问题",
    privacyPolicy: "隐私政策"
  },
  zh_TW: {
    title: "小米帳號登入",
    accountPlaceholderSMS: "手機號碼",
    accountPlaceholder: "E-mail/手機號碼/小米ID",
    passwordPlaceholderSMS: "短信驗證碼",
    passwordPlaceholder: "密碼",
    codeMsg: "獲取驗證碼",
    codeMsgRetry: "重新發送",
    loginBtnSMS: "立即登錄/注冊",
    loginBtn: "登入",
    toggleBtnSMS: "用戶名密碼登錄",
    toggleBtn: "手機短信登錄/注冊",
    errMsgEmptyVerificationCode: "請輸入簡訊驗證碼",
    errMsgInvalidVerificationCode: "短信驗證碼不正確",
    errMsgEmptyPhoneNumber: "請輸入手機號",
    errMsgInvalidPhoneNumber: "手機號格式不正確",
    errMsgEmptyAccount: "請輸入帳號名",
    errMsgEmptyPassword: "請輸入密碼",
    registerTip: "立即註冊",
    forgotPassword: "忘記密碼?",
    otherLoginType: "其他登入方式",
    FAQ: "常見問題",
    privacyPolicy: "隱私政策"
  },
  en_US: {
    title: "Sign in to your Mi Account",
    accountPlaceholderSMS: "Phone number",
    accountPlaceholder: "Email/Phone/Mi Account",
    passwordPlaceholderSMS: "Verification code",
    passwordPlaceholder: "Password",
    codeMsg: "Get verification code",
    codeMsgRetry: "Resend",
    loginBtnSMS: "Sign in/Sign up",
    loginBtn: "Sign in",
    toggleBtnSMS: "Sign in with password",
    toggleBtn: "Sign in with SMS",
    errMsgEmptyVerificationCode: "Enter code",
    errMsgInvalidVerificationCode: "The code is invalid",
    errMsgEmptyPhoneNumber: "Enter phone number",
    errMsgInvalidPhoneNumber: "The phone number is invalid",
    errMsgEmptyAccount: "Enter your email address or phone number",
    errMsgEmptyPassword: "Enter your password",
    registerTip: "Create account",
    forgotPassword: "Forgot password?",
    otherLoginType: "More options",
    FAQ: "FAQ",
    privacyPolicy: "Privacy Policy"
  }
};

export default pageContent;
